Create PULL_REQUEST_TEMPLATE.md
Showrin/nextjs-tailwind-storybook-with-ci-cd pull request #18
Opened 2023-06-04 03:12 UTC by Anirudh3167

# Motive
The PR template created

# Issue this PR is related
Reffers to Issue: #12

https://github.com/Showrin/nextjs-tailwind-storybook-with-ci-cd/issues/12

# Additional Description
comments are added in the `PULL_REQUEST_TEMPLATE.md` to clear the intention of adding each and every heading

2023-06-11 20:07 UTC, Showrin requested changes
Please, write the commit messages following this **[commit convention](https://www.conventionalcommits.org/en/v1.0.0-beta.4/)**. Thanks for the contribution.

2023-06-11 20:07 UTC, Showrin commented on PULL_REQUEST_TEMPLATE.md
> +<!-- A PR can either be an issue or it is independently made changes -->
```suggestion
# Issue
N/A <!-- A PR can either be an issue or it independently made changes. If it's created to resolve an issue, please provide the issue number in this format - (#issue_number) -->

# Description
<!-- Detailing of the problem that this PR is solving -->
```

2023-06-11 20:07 UTC, Showrin commented on PULL_REQUEST_TEMPLATE.md
> +- [ ] The pull request title provides a concise summary of the changes.
```suggestion
- [ ] The pull request title concisely summarizes the changes.
```

2023-06-14 11:40 UTC, Anirudh3167 commented
I have edited the file as you suggested

This time I have also added a screenshots section

so as to make it easy for the reviewer to know about the frontend changes

2023-06-24 09:03 UTC, Showrin commented
> I have edited the file as you suggested
> 
> This time I have also added a screenshots section
> 
> so as to make it easy for the reviewer to know about the frontend changes

Thanks, @Anirudh3167 for the contribution.

2023-06-24 09:03 UTC, Showrin approved these changes

2023-06-24 09:04 UTC, merged